services:
  gateway:
    image: akhrustal/gateway
    build: ./gateway/
    ports:
      - "8080:8080"

  reservation:
    image: akhrustal/reservation
    build: ./reservation/
    ports:
      - "8070:8070"

  library:
    image: akhrustal/library
    build: ./library/
    ports:
      - "8060:8060"

  rating:
    image: akhrustal/rating
    build: ./rating/
    ports:
      - "8050:8050"

volumes:
  db-data: