server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

services:
  ports:
    reservation: 8070
    library: 8060
    rating: 8050

okta:
  oauth2:
    issuer: https://dev-67293951.okta.com/oauth2/default
    client-id: 0oa7v6iuxgML1dPu95d7
    client-secret: _u1P0Iy4ahy0EfXtVPkS794E5ApwV5yhSNxmjOen
    redirect-uri: http://51.250.8.40/api/v1/callback/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-67293951.okta.com/oauth2/default/v1/keys